-- Data module for the Common Resource guide.
-- GENERATED by scripts/common_resource/generate_common_resource.py from the ecgc-dev
-- CommonResourceData TypeScript source. DO NOT EDIT BY HAND.
-- Regenerate with: uv run scripts/common_resource/generate_common_resource.py <dump.json>
-- Schema per resource: name, category, icon (wikitext), link (wiki page),
--   drops = { { group, color, mark, optimal, locations = { { name, link,
--     amount (number or 'RNG'), timeFrame, notes } } } }, notes.
-- timeFrame values: daily, weekly, monthly, bimonthly, one-time, chapter,
--   cycle, or nil.

return {
  infinite = {
    {
      name = 'Coin',
      category = 'Currency',
      icon = '{{Display|Coinicon|N|Coin|50}}',
      link = 'Shops',
      drops = {
        {
          group = 'academy',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Merchant',
              link = 'Living_Area#Canteen_and_Merchant',
              amount = 7776,
              timeFrame = 'daily',
            },
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Login Rewards',
              link = 'Missions#Login Rewards',
              amount = 4800,
              timeFrame = 'monthly',
            },
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 2300,
              timeFrame = 'daily',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 14000,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 14000,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'All Daily Raids',
              link = 'Daily_Raid',
              amount = 'RNG',
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions',
              link = 'Cruise_Missions#Rewards',
              amount = 24000,
              timeFrame = 'bimonthly',
              notes = 'Free',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Campaign Chapters 9+',
              link = 'Campaign',
              amount = 'RNG',
              timeFrame = nil,
              notes = 'Clearing Rewards',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Event Chapter D',
              link = 'Events',
              amount = 'RNG',
              timeFrame = nil,
              notes = 'Clearing Rewards',
            },
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 1000,
              timeFrame = 'cycle',
              notes = '3000 Points',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Exchange Shop',
              link = 'Operation_Siren#Exchange_Shop',
              amount = 10000,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 10000,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 770160, monthly = 373080, weekly = 93270, daily = 12436, oneTime = 14000 },
    },
    {
      name = 'Oil',
      category = 'Currency',
      icon = '{{Display|Oilicon|N|Oil|50}}',
      link = 'Oil_Cost',
      drops = {
        {
          group = 'academy',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Canteen',
              link = 'Living_Area#Canteen_and_Merchant',
              amount = 2304,
              timeFrame = 'daily',
            },
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Login Rewards',
              link = 'Missions#Login Rewards',
              amount = 1500,
              timeFrame = 'monthly',
            },
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 520,
              timeFrame = 'daily',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 2900,
              timeFrame = 'weekly',
            },
            {
              name = 'Weekly Free Supplies Pack',
              link = 'Akashi\'s Shop#Packs',
              amount = 4000,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 9300,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 5000,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 227640, monthly = 113820, weekly = 28455, daily = 3794, oneTime = 9300 },
    },
    {
      name = 'Core Data',
      category = 'Currency',
      icon = '{{Display|Core Data|R|Core Data|50}}',
      link = 'Shops#Core_Exchange',
      drops = {
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 5,
              timeFrame = 'daily',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 15,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 1600,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'hardModeDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Campaign Hard Mode',
              link = 'Combat#Hard_Mode',
              amount = 90,
              timeFrame = 'daily',
            },
          },
        },
      },
      total = { bimonthly = 5820, monthly = 2910, weekly = 727, daily = 97, oneTime = 1600 },
      notes = 'Check [[Combat#Hard_Mode|this Wiki page]] for lower Chapter drop information.',
    },
    {
      name = 'Guild Token',
      category = 'Currency',
      icon = '{{Display|GuildToken|R|Guild Token|50}}',
      link = 'Guild',
      drops = {
        {
          group = 'academy',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Guild Missions',
              link = 'Guild#Logistics',
              amount = 400,
              timeFrame = 'weekly',
            },
            {
              name = 'Guild Operations',
              link = 'Guild#Operations',
              amount = 1000,
              timeFrame = 'weekly',
            },
            {
              name = 'Guild Contributions',
              link = 'Guild#Logistics',
              amount = 255,
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 50,
              timeFrame = 'daily',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 200,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 500,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions',
              link = 'Cruise_Missions#Rewards',
              amount = 400,
              timeFrame = 'bimonthly',
              notes = 'Free',
            },
          },
        },
      },
      total = { bimonthly = 31500, monthly = 15550, weekly = 3887, daily = 518, oneTime = 500 },
    },
    {
      name = 'Crystal Fragment',
      category = 'Currency',
      icon = '{{Display|Crystal Fragment|SR|Crystal Fragment|50}}',
      link = 'Shops#META_Shop',
      drops = {
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 8,
              timeFrame = 'weekly',
            },
            {
              name = 'One-Time Missions',
              link = 'Shops#Crystal_Fragment_Missions',
              amount = 240,
              timeFrame = 'one-time',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Exchange Shop',
              link = 'Operation_Siren#Exchange_Shop',
              amount = 10,
              timeFrame = 'monthly',
            },
            {
              name = 'Arbiter',
              link = 'Operation_Siren#Arbiter',
              amount = 20,
              timeFrame = 'monthly',
              notes = 'Normal & Hard',
            },
          },
        },
      },
      total = { bimonthly = 124, monthly = 62, weekly = 15, daily = 2, oneTime = 240 },
    },
    {
      name = 'Prototype Core',
      category = 'Currency',
      icon = '{{Display|Protocoreicon|SR|Prototype Core|50}}',
      link = 'Shops#Prototype_Shop',
      drops = {
        {
          group = 'academy',
          color = 'red',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Contributions',
              link = 'Guild#Logistics',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Development Missions',
              amount = 5600,
              timeFrame = 'one-time',
              notes = 'Dev.',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 200,
              timeFrame = 'bimonthly',
            },
          },
        },
      },
      total = { bimonthly = 200, monthly = 100, weekly = 0, daily = 0, oneTime = 5600 },
      notes = 'Read Protocore Income for more information.',
    },
    {
      name = 'Wisdom Cube',
      category = 'Currency',
      icon = '{{Display|Wisdom Cube|SR|Wisdom Cube}}',
      link = 'Construction',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Login Rewards',
              link = 'Missions#Login Rewards',
              amount = 30,
              timeFrame = 'monthly',
            },
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 3,
              timeFrame = 'daily',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 12,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook',
              amount = 148,
              timeFrame = 'one-time',
              notes = '80 Rookie {{!}} 68 Mechanic',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 20,
              timeFrame = 'bimonthly',
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'Shops#General Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'meritShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Merit Shop',
              link = 'Shops#Merit Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
      },
      total = { bimonthly = 356, monthly = 168, weekly = 42, daily = 5, oneTime = 148 },
      notes = 'Total income is likely way higher due to Commission RNG.',
    },
    {
      name = 'T1 EXP Data Pack',
      category = 'Consumable',
      icon = '{{Display|T1EXP|R|T1 EXP Data Pack|50}}',
      link = 'Experience#Ship_XP',
      drops = {
        {
          group = 'academy',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Lecture Hall',
              link = 'Living_Area#Lecture_Hall',
              amount = 52,
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Weekly Free Supplies Pack',
              link = 'Akashi\'s Shop#Packs',
              amount = 20,
              timeFrame = 'weekly',
            },
            {
              name = 'Missions - Side',
              link = 'Beginner_Rewards#Side_Quests',
              amount = 900,
              timeFrame = 'one-time',
              notes = 'Total Rewards',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 600,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Tactical Training',
              link = 'Daily_Raid#Tactical_Training',
              amount = 6,
              timeFrame = 'daily',
              notes = 'Lv.100',
            },
            {
              name = 'Supply Line Disruption',
              link = 'Daily_Raid#Supply_Line_Disruption',
              amount = 8,
              timeFrame = 'weekly',
              notes = 'Lv.95',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 120,
              timeFrame = 'bimonthly',
            },
          },
        },
      },
      total = { bimonthly = 3824, monthly = 1852, weekly = 463, daily = 61, oneTime = 1500 },
    },
    {
      name = 'High-Efficiency Combat Logistics Plan',
      category = 'Consumable',
      icon = '{{Display|High-Efficiency Combat Logistics Plan|P|High-Efficiency Combat Logistics Plan|50}}',
      link = 'Combat#High-Efficiency_Combat_Logistics_Plan',
      drops = {
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Weekly Free Supplies Pack',
              link = 'Akashi%27s_Shop#Packs',
              amount = 10,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Exchange Shop',
              link = 'Operation_Siren#Exchange_Shop',
              amount = 30,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 140, monthly = 70, weekly = 17, daily = 2, oneTime = 'N/A' },
      notes = 'Usually given via Mail after Server Maintenance.',
    },
    {
      name = 'Cognitive Chip',
      category = 'Cognitive Awakening',
      icon = '{{Display|Cognitive Chip|SR|Cognitive Chip|50}}',
      link = 'Dockyard#Cognitive_Awakening',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Missions - Side',
              link = 'Beginner_Rewards#Side_Quests',
              amount = 4200,
              timeFrame = 'one-time',
              notes = 'Total Rewards',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Tactical Training',
              link = 'Daily_Raid#Tactical_Training',
              amount = 210,
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 400,
              timeFrame = 'bimonthly',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Chapter 12+',
              link = 'Campaign',
              amount = 'RNG',
              timeFrame = nil,
              notes = 'Clearing Rewards',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 1900,
              timeFrame = 'cycle',
              notes = '12000 Points',
            },
          },
        },
        {
          group = 'coreDataShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Core Data (Mo.)',
              link = 'Shops#Core_Shop_(Mo.)',
              amount = 1000,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'Shops#Guild_Shop',
              amount = 200,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 1000,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 15000, monthly = 7300, weekly = 1825, daily = 243, oneTime = 4200 },
      notes = 'Cognitive Chip commissions unlock once any ship reaches Lv.100.',
    },
    {
      name = 'Cognitive Array',
      category = 'Cognitive Awakening',
      icon = '{{Display|Cognitive Array|SR|Cognitive Array|50}}',
      link = 'Dockyard#Cognitive_Awakening',
      drops = {
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Missions - Side',
              link = 'Beginner_Rewards#Side_Quests',
              amount = 1150,
              timeFrame = 'one-time',
              notes = 'Total Rewards',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Tactical Training',
              link = 'Daily_Raid#Tactical_Training',
              amount = 9,
              timeFrame = 'daily',
              notes = 'Lv.100',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 150,
              timeFrame = 'bimonthly',
            },
          },
        },
        {
          group = 'coreDataShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Core Data (Mo.)',
              link = 'Shops#Core_Shop_(Mo.)',
              amount = 50,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 50,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 790, monthly = 320, weekly = 80, daily = 10, oneTime = 1150 },
    },
    {
      name = 'Universal Bulin',
      category = 'Bulin',
      icon = '{{Display|Universal BulinIcon|P|Universal Bulin|50}}',
      link = 'Dockyard#Limit_Break',
      drops = {
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Login Rewards',
              link = 'Missions#Login Rewards',
              amount = 3,
              timeFrame = 'monthly',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 3,
              timeFrame = 'weekly',
            },
            {
              name = 'Level-Up Rewards',
              link = 'Beginner_Rewards#Level-Up',
              amount = 2,
              timeFrame = 'one-time',
              notes = 'Lv.20, Lv.30',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 4,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'X-2 Stages',
              link = 'Campaign',
              amount = 1,
              timeFrame = 'chapter',
              notes = '3-Star Reward',
            },
          },
        },
        {
          group = 'meritShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Merit Shop',
              link = 'Shops#Merit_Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'Daily',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Medal_Shop',
              amount = 10,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 50, monthly = 25, weekly = 6, daily = 0, oneTime = 21 },
      notes = 'Only buy as much as you need.',
    },
    {
      name = 'Prototype Bulin MKII',
      category = 'Bulin',
      icon = '{{Display|Prototype Bulin MKIIIcon|SR|Prototype Bulin MKII|50}}',
      link = 'Dockyard#Limit_Break',
      drops = {
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Login Rewards',
              link = 'Missions#Login Rewards',
              amount = 1,
              timeFrame = 'monthly',
            },
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 1,
              timeFrame = 'weekly',
            },
            {
              name = 'Level-Up Rewards',
              link = 'Beginner_Rewards#Level-Up',
              amount = 2,
              timeFrame = 'one-time',
              notes = 'Lv.40, Lv.50',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 4,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'X-4 Stages',
              link = 'Campaign',
              amount = 1,
              timeFrame = 'chapter',
              notes = '3-Star Reward',
            },
          },
        },
        {
          group = 'meritShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Merit Shop',
              link = 'Shops#Merit_Shop',
              amount = 2,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Medal_Shop',
              amount = 2,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 18, monthly = 9, weekly = 2, daily = 0, oneTime = 21 },
      notes = 'You can get up to 4 from [[Merit_Shop|Merit Shop]] depending on your performance.',
    },
    {
      name = 'Specialized Bulin Custom MKIII',
      category = 'Bulin',
      icon = '{{Display|Specialized Bulin Custom MKIIIIcon|UR|Specialized Bulin Custom MKIII|50}}',
      link = 'Dockyard#Limit_Break',
      drops = {
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Bulin Support Plan',
              link = 'Beginner_Rewards#Bulin_Support_Plan',
              amount = 1.5,
              timeFrame = 'one-time',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 1,
              timeFrame = 'bimonthly',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Prototype_Shop',
              amount = 0.75,
              timeFrame = 'monthly',
              notes = 'Specialized Core',
            },
          },
        },
        {
          group = 'prototypeShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Prototype Shop',
              link = 'Shops#Prototype_Shop',
              amount = 1.25,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 5, monthly = 2, weekly = 0, daily = 0, oneTime = 1.5 },
      notes = 'Assuming \'\'\'6\'\'\' new UR Ships per Year, you need \'\'\'24\'\'\' bulins to MLB all of them.<br />[[Prototype_Shop|Prototype Shop]] has no purchase limit.',
    },
    {
      name = 'T1 Plate',
      category = 'Gear Enhance',
      icon = '{{Display|UnknownT1Plate|N|T1 Plate|50}}',
      link = 'Equipment#Upgrade_(Enhance)',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 20,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Escort Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Escort_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'all but Lv.95',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Chapters 1-12',
              link = 'https://azurlane.koumakan.jp/wiki/Campaign',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'All Event Chapters',
              link = 'https://azurlane.koumakan.jp/wiki/Events',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 5,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Medal_Shop',
              amount = 300,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T2 Plate',
      category = 'Gear Enhance',
      icon = '{{Display|UnknownT2Plate|R|T2 Plate|50}}',
      link = 'Equipment#Upgrade_(Enhance)',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 5,
              timeFrame = 'daily',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 50,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Escort Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Escort_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'Lv.25+',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Chapters 3+',
              link = 'https://azurlane.koumakan.jp/wiki/Campaign',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'All Event Chapters',
              link = 'https://azurlane.koumakan.jp/wiki/Events',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 5,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Guild_Shop',
              amount = 5,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Medal_Shop',
              amount = 300,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T3 Plate',
      category = 'Gear Enhance',
      icon = '{{Display|UnknownT3Plate|P|T3 Plate|50}}',
      link = 'Equipment#Upgrade_(Enhance)',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 10,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 60,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Escort Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Escort_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'Lv.50+',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions',
              link = 'Cruise_Missions#Rewards',
              amount = 100,
              timeFrame = 'bimonthly',
              notes = 'Free',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Chapters 6+',
              link = 'https://azurlane.koumakan.jp/wiki/Campaign',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Event Chapters C+',
              link = 'https://azurlane.koumakan.jp/wiki/Events',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 5,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Guild_Shop',
              amount = 5,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Medal_Shop',
              amount = 120,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 150,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'General Plates might be a concern, rest aren\'t.\'\'\'',
    },
    {
      name = 'T4 Plate',
      category = 'Gear Enhance',
      icon = '{{Display|UnknownT4Plate|SR|T4 Plate|50}}',
      link = 'Equipment#Upgrade_(Enhance)',
      drops = {
        {
          group = 'academy',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Operations',
              link = 'Guild#Operations',
              amount = 36,
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 4,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Escort Mission',
              link = 'Daily_Raid#Escort_Mission',
              amount = 9,
              timeFrame = 'weekly',
              notes = 'Lv.95',
            },
            {
              name = 'Supply Line Disruption',
              link = 'Daily_Raid#Supply_Line_Disruption',
              amount = 9,
              timeFrame = 'weekly',
              notes = 'Lv.95',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 30,
              timeFrame = 'bimonthly',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 20,
              timeFrame = 'cycle',
              notes = '55000 Points',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Blue Port Shops',
              link = 'Operation_Siren#Ports',
              amount = 30,
              timeFrame = 'monthly',
            },
            {
              name = 'Arbiter',
              link = 'Operation_Siren#Arbiter',
              amount = 60,
              timeFrame = 'monthly',
              notes = 'Normal + Hard',
            },
            {
              name = 'Strongholds',
              link = 'Operation_Siren#Siren_Stronghold',
              amount = 'RNG',
              timeFrame = 'monthly',
            },
            {
              name = 'Coordinate Zones',
              link = 'Operation_Siren#Abyssal',
              amount = 'RNG',
              timeFrame = 'monthly',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Guild Shop',
              link = 'Shops#Guild_Shop',
              amount = 20,
              timeFrame = 'weekly',
            },
          },
        },
      },
      total = { bimonthly = 618, monthly = 294, weekly = 73, daily = 9, oneTime = 'N/A' },
      notes = 'Total income is likely way higher due to OpSi RNG.',
    },
    {
      name = 'Augment Module Core',
      category = 'Augmentation',
      icon = '{{Display|Augment Module Core|SR|Augment Module Core|50}}',
      link = 'Augmentation#Crafting_and_Enhancing',
      drops = {
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 10,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Module Development',
              link = 'Daily_Raid#Module Development',
              amount = 2,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions',
              link = 'Cruise_Missions#Rewards',
              amount = 5,
              timeFrame = 'bimonthly',
              notes = 'Free',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 5,
              timeFrame = 'cycle',
              notes = '25000 Points',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Arbiter',
              link = 'Operation_Siren#Arbiter',
              amount = 5,
              timeFrame = 'monthly',
              notes = 'Normal',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 5,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 31, monthly = 13, weekly = 3, daily = 0, oneTime = 10 },
    },
    {
      name = 'Augment Module EXP',
      category = 'Augmentation',
      icon = '{{Display|T1 Augment Module Stone|R|Augment Module Stone T1|50}} {{Display|T2 Augment Module Stone|E|Augment Module Stone T2|50}} {{Display|T3 Augment Module Stone|SR|Augment Module Stone T3|50}}',
      link = 'Augmentation#Crafting_and_Enhancing',
      drops = {
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 1000,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Module Development',
              link = 'Daily_Raid#Module Development',
              amount = 4000,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions',
              link = 'Cruise_Missions#Rewards',
              amount = 1000,
              timeFrame = 'bimonthly',
              notes = 'Free',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Campaign Chapters 12+',
              link = 'Campaign',
              amount = 'RNG',
              timeFrame = nil,
              notes = 'Clearing Rewards',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 11000,
              timeFrame = 'cycle',
              notes = '45000 Points',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 5000,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 33000, monthly = 16000, weekly = 4000, daily = 533, oneTime = 1000 },
      notes = 'Purple & Gold Rarity only drop on Chapters 13/14+ respectively.<br />You can use extra Augment Modules for enhancement. See [[Augmentation|Augmentation]] for more details.',
    },
    {
      name = 'T1 Augment Conversion',
      category = 'Augmentation',
      icon = '{{Display|T1 Augment Module Conversion Stone|E|Augment Module Conversion Stone T1|50}}',
      link = 'Augmentation#Convertion',
      drops = {
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Module Development',
              link = 'Daily_Raid#Module Development',
              amount = 4,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 10,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 32, monthly = 16, weekly = 4, daily = 0, oneTime = 'N/A' },
    },
    {
      name = 'T2 Augment Conversion',
      category = 'Augmentation',
      icon = '{{Display|T2 Augment Module Conversion Stone|SR|Augment Module Conversion Stone T2|50}}',
      link = 'Augmentation#Convertion',
      drops = {
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Module Development',
              link = 'Daily_Raid#Module Development',
              amount = 2,
              timeFrame = 'weekly',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 5,
              timeFrame = 'cycle',
              notes = '17500 Points',
            },
          },
        },
        {
          group = 'eventShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Limited Event Shop',
              link = 'Shops#Event_Shop',
              amount = 2,
              timeFrame = 'cycle',
            },
          },
        },
      },
      total = { bimonthly = 16, monthly = 8, weekly = 2, daily = 0, oneTime = 'N/A' },
    },
    {
      name = 'T1 Retrofit Blueprint',
      category = 'Retrofit',
      icon = '{{Display|UnknownT1BP|R|T1 Retrofit Blueprint|50}}',
      link = 'Dockyard#Retrofit',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 2,
              timeFrame = 'daily',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 20,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'hardModeDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Campaign Hard Mode',
              link = 'Combat#Hard_Mode',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Medal_Shop',
              amount = 24,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T2 Retrofit Blueprint',
      category = 'Retrofit',
      icon = '{{Display|UnknownT2BP|P|T2 Retrofit Blueprint|50}}',
      link = 'Dockyard#Retrofit',
      drops = {
        {
          group = 'academy',
          color = 'red',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 20,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'hardModeDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Campaign Hard Mode',
              link = 'Combat#Hard_Mode',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 4,
              timeFrame = 'cycle',
              notes = '2500 Points; 1 Each',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'Shops#Guild_Shop',
              amount = 2,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Medal_Shop',
              amount = 12,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T3 Retrofit Blueprint',
      category = 'Retrofit',
      icon = '{{Display|UnknownT3BP|SR|T3 Retrofit Blueprint|50}}',
      link = 'Dockyard#Retrofit',
      drops = {
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 10,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'hardModeDrop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Campaign Hard Mode',
              link = 'Combat#Hard_Mode',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 9,
              timeFrame = 'cycle',
              notes = '13000 Points; 1 Each + 5 Random',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'Shops#Guild_Shop',
              amount = 2,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Medal Shop',
              link = 'Shops#Medal_Shop',
              amount = 4,
              timeFrame = 'monthly',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Cruiser Prints might be a concern, rest aren\'t.\'\'\'',
    },
    {
      name = 'T1 Skill Book',
      category = 'Skill Book',
      icon = '{{Display|UnknownT1Book|R|T1 Skill Book}}',
      link = 'https://azurlane.koumakan.jp/wiki/Living_Area#Tactical_Class',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Daily Missions',
              link = 'Missions#Daily_Missions',
              amount = 2,
              timeFrame = 'daily',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Advance Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Advance_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'all but Lv.95',
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T2 Skill Book',
      category = 'Skill Book',
      icon = '{{Display|UnknownT2Book|P|T2 Skill Book}}',
      link = 'https://azurlane.koumakan.jp/wiki/Living_Area#Tactical_Class',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 10,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Advance Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Advance_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'Lv.25+',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 5,
              timeFrame = 'cycle',
              notes = '100 Points',
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Guild_Shop',
              amount = 3,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Medal Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Medal_Shop',
              amount = 18,
              timeFrame = 'monthly',
              notes = '6 Each',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Not a concern.\'\'\'',
    },
    {
      name = 'T3 Skill Book',
      category = 'Skill Book',
      icon = '{{Display|UnknownT3Book|SR|T3 Skill Book}}',
      link = 'https://azurlane.koumakan.jp/wiki/Living_Area#Tactical_Class',
      drops = {
        {
          group = 'academy',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'https://azurlane.koumakan.jp/wiki/Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Weekly Missions',
              link = 'Missions#Weekly_Missions',
              amount = 1,
              timeFrame = 'weekly',
            },
            {
              name = 'Commander Handbook',
              link = 'Commander Handbook#Rookie Missions',
              amount = 10,
              timeFrame = 'one-time',
              notes = 'Rookie',
            },
          },
        },
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Advance Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Advance_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'Lv.50+',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 15,
              timeFrame = 'bimonthly',
              notes = '5 Each',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 8,
              timeFrame = 'cycle',
              notes = '1100 Points; 2 Each + 2 Random',
            },
          },
        },
        {
          group = 'generalShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'General Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#General_Shop',
              amount = 1,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'guildShop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Guild Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Guild_Shop',
              amount = 3,
              timeFrame = 'cycle',
              notes = 'RNG',
            },
          },
        },
        {
          group = 'medalShop',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Medal Shop',
              link = 'https://azurlane.koumakan.jp/wiki/Shops#Medal_Shop',
              amount = 6,
              timeFrame = 'monthly',
              notes = '2 Each',
            },
          },
        },
      },
      total = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
      notes = '\'\'\'Offensive Skill Books might be a concern, rest aren\'t.\'\'\'',
    },
    {
      name = 'T4 Skill Book',
      category = 'Skill Book',
      icon = '{{Display|UnknownT4Book|UR|T4 Skill Book}}',
      link = 'https://azurlane.koumakan.jp/wiki/Living_Area#Tactical_Class',
      drops = {
        {
          group = 'dailyRaid',
          color = 'green',
          mark = 'check',
          optimal = true,
          locations = {
            {
              name = 'Advance Mission',
              link = 'https://azurlane.koumakan.jp/wiki/Daily_Raid#Advance_Mission',
              amount = 'RNG',
              timeFrame = 'daily',
              notes = 'Lv.95',
            },
          },
        },
        {
          group = 'cruisePass',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Cruise Missions (Free)',
              link = 'Cruise_Missions#Rewards',
              amount = 4,
              timeFrame = 'bimonthly',
              notes = 'Random',
            },
          },
        },
        {
          group = 'eventDrop',
          color = 'sand',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Event Point Milestone',
              link = 'Events',
              amount = 2,
              timeFrame = 'cycle',
              notes = '70000 Points; Random',
            },
          },
        },
        {
          group = 'opsi',
          color = 'green',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Exchange Shop',
              link = 'Operation_Siren#Exchange_Shop',
              amount = 6,
              timeFrame = 'monthly',
              notes = '2 Each',
            },
          },
        },
      },
      total = { bimonthly = 16, monthly = 6, weekly = 1, daily = 0, oneTime = 'N/A' },
    },
  },
  finite = {
    {
      name = 'Gem',
      category = 'Currency',
      icon = '{{Display|Ruby|P|Gems|50}}',
      link = 'Akashi\'s_Shop#Gems',
      drops = {
        {
          group = 'academy',
          color = 'red',
          mark = 'check',
          optimal = nil,
          locations = {
            {
              name = 'Commissions',
              link = 'Commissions',
              amount = 'RNG',
              timeFrame = nil,
            },
          },
        },
        {
          group = 'missions',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Beginner Rewards',
              link = 'Beginner_Rewards#8-Day_Login_Rewards',
              amount = 150,
              timeFrame = 'one-time',
              notes = '8-Day Login',
            },
            {
              name = 'Memento',
              link = 'List_of_Collections',
              amount = 800,
              timeFrame = 'one-time',
              notes = 'Collections',
            },
            {
              name = 'Character Collection',
              link = 'Island_Planner',
              amount = 150,
              timeFrame = 'one-time',
            },
            {
              name = 'Achievements',
              link = 'Island_Planner',
              amount = 1180,
              timeFrame = 'one-time',
            },
            {
              name = 'Stellar Prize Draw',
              link = 'Island_Planner',
              amount = 'RNG',
              timeFrame = nil,
              notes = 'Extra tickets convert to gems once the prize pool is exhausted',
            },
          },
        },
        {
          group = 'campaignDrop',
          color = 'sand',
          mark = 'x',
          optimal = nil,
          locations = {
            {
              name = 'Campaign Stages (X-1, X-2, X-3)',
              link = 'Campaign',
              amount = 150,
              timeFrame = 'chapter',
              notes = '3-Star Reward',
            },
            {
              name = 'Campaign Stages (X-4)',
              link = 'Campaign',
              amount = 100,
              timeFrame = 'chapter',
              notes = '3-Star Reward',
            },
          },
        },
      },
      total = { bimonthly = 0, monthly = 0, weekly = 0, daily = 0, oneTime = 6030 },
      notes = 'Collection, achievement, and prize draw amounts per the [[Island Planner]] page',
    },
  },
}
