-- Expected totals as computed by the ecgc-dev TypeScript getTotalGuaranteed.
-- GENERATED by scripts/common_resource/generate_common_resource.py. Used by scripts/common_resource/run_tests.lua.
-- oneTime uses the string 'N/A' where the TS side reports N/A.

return {
  infinite = {
    ['Coin'] = { bimonthly = 770160, monthly = 373080, weekly = 93270, daily = 12436, oneTime = 14000 },
    ['Oil'] = { bimonthly = 227640, monthly = 113820, weekly = 28455, daily = 3794, oneTime = 9300 },
    ['Core Data'] = { bimonthly = 5820, monthly = 2910, weekly = 727, daily = 97, oneTime = 1600 },
    ['Guild Token'] = { bimonthly = 31500, monthly = 15550, weekly = 3887, daily = 518, oneTime = 500 },
    ['Crystal Fragment'] = { bimonthly = 124, monthly = 62, weekly = 15, daily = 2, oneTime = 240 },
    ['Prototype Core'] = { bimonthly = 200, monthly = 100, weekly = 0, daily = 0, oneTime = 5600 },
    ['Wisdom Cube'] = { bimonthly = 356, monthly = 168, weekly = 42, daily = 5, oneTime = 148 },
    ['T1 EXP Data Pack'] = { bimonthly = 3824, monthly = 1852, weekly = 463, daily = 61, oneTime = 1500 },
    ['High-Efficiency Combat Logistics Plan'] = { bimonthly = 140, monthly = 70, weekly = 17, daily = 2, oneTime = 'N/A' },
    ['Cognitive Chip'] = { bimonthly = 15000, monthly = 7300, weekly = 1825, daily = 243, oneTime = 4200 },
    ['Cognitive Array'] = { bimonthly = 790, monthly = 320, weekly = 80, daily = 10, oneTime = 1150 },
    ['Universal Bulin'] = { bimonthly = 50, monthly = 25, weekly = 6, daily = 0, oneTime = 21 },
    ['Prototype Bulin MKII'] = { bimonthly = 18, monthly = 9, weekly = 2, daily = 0, oneTime = 21 },
    ['Specialized Bulin Custom MKIII'] = { bimonthly = 5, monthly = 2, weekly = 0, daily = 0, oneTime = 1.5 },
    ['T1 Plate'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T2 Plate'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T3 Plate'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T4 Plate'] = { bimonthly = 618, monthly = 294, weekly = 73, daily = 9, oneTime = 'N/A' },
    ['Augment Module Core'] = { bimonthly = 31, monthly = 13, weekly = 3, daily = 0, oneTime = 10 },
    ['Augment Module EXP'] = { bimonthly = 33000, monthly = 16000, weekly = 4000, daily = 533, oneTime = 1000 },
    ['T1 Augment Conversion'] = { bimonthly = 32, monthly = 16, weekly = 4, daily = 0, oneTime = 'N/A' },
    ['T2 Augment Conversion'] = { bimonthly = 16, monthly = 8, weekly = 2, daily = 0, oneTime = 'N/A' },
    ['T1 Retrofit Blueprint'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T2 Retrofit Blueprint'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T3 Retrofit Blueprint'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T1 Skill Book'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T2 Skill Book'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T3 Skill Book'] = { bimonthly = 'N/A', monthly = 'N/A', weekly = 'N/A', daily = 'N/A', oneTime = 'N/A' },
    ['T4 Skill Book'] = { bimonthly = 16, monthly = 6, weekly = 1, daily = 0, oneTime = 'N/A' },
  },
  finite = {
    ['Gem'] = { bimonthly = 0, monthly = 0, weekly = 0, daily = 0, oneTime = 6030 },
  },
}
